#!/usr/bin/env python

import cli.app

@cli.app.ComandLineApp
def commandlineapp(app):
    write = lambda msg, s=app.stdout: s.write(msg + "\n")
    write("This is a command line application")
    write("It has some parameters")
    write("Here's foo: %s" % app.params.foo)
    if app.params.bar:
        write("We got bar")

commandlineapp.add_param("foo", help="this is a mandatory positional parameter")
commandlineapp.add_param("-b", "--bar", default=False, action="store_true",
    help="this is an optional parameter")

if __name__ == "__main__":
    commandlineapp.run()
