#!/usr/bin/env python
import cli.daemon

@cli.daemon.DaemonizingApp
def daemon(app):
    if app.params.daemonize:
        app.log.info("About to daemonize")
        app.daemonize()

if __name__ == "__main__":
    daemon.run()
